site_name: OneBot v12 标准文档
repo_name: botuniverse/onebot
repo_url: https://github.com/botuniverse/onebot
edit_uri: blob/v12-draft/v12/docs/
theme:
  name: material
  custom_dir: material
  language: zh
  logo: assets/logo-white.png
  favicon: assets/logo.png
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
extra:
  search:
    language: jp # 不支持中文，改成日文好像能搜到一部分中文了（无语）
  analytics:
    provider: google
    property: G-7GZP8RMCBB
extra_javascript:
  - javascripts/config.js

nav:
  - 主页: index.md
  - 介绍: production.md
  - 生态:
    - OneBot 实现 / LibOneBot: ecosystem/libonebot.md
    - OneBot 开发框架 / SDK: ecosystem/onebot-sdk.md
    - OneBot 应用案例: ecosystem/onebot-application.md
  - 指南:
    - 概述:
      - 术语表: specs/glossary/index.md
    - OneBot RPC:
      - 通信:
        - 通信概述: specs/communication/index.md
        - HTTP: specs/communication/http.md
        - HTTP Webhook: specs/communication/http-webhook.md
        - 正向 WebSocket: specs/communication/websocket.md
        - 反向 WebSocket: specs/communication/websocket-reverse.md
      - 数据协议:
        - 事件: specs/onebot-rpc/event.md
        - 动作: specs/onebot-rpc/action.md
        - 动作响应: specs/onebot-rpc/action-response.md
        - 错误码: specs/onebot-rpc/retcode.md
    - 标准接口:
      - 事件: specs/event/index.md
      - 动作: specs/action/index.md
      - 消息: specs/message/index.md
