name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - v12-draft

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v12-draft
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: v12/mkdocs.yml
          EXTRA_PACKAGES: build-base

